#!/bin/bash

echo "🔐 GitHub CLI Authentication Helper"
echo "=================================="
echo ""
echo "ขั้นตอนที่ 1: สร้าง Personal Access Token"
echo "1. เปิด: https://github.com/settings/tokens/new"
echo "2. ตั้งชื่อ: OneEvent Auto Deploy"
echo "3. เลือก Scopes:"
echo "   ✅ repo"
echo "   ✅ workflow" 
echo "   ✅ write:packages"
echo "   ✅ delete:packages"
echo "   ✅ admin:org"
echo "4. คลิก Generate token"
echo "5. Copy token ที่ได้"
echo ""
echo "ขั้นตอนที่ 2: Login ด้วย Token"
echo "รันคำสั่งนี้และ paste token เมื่อถูกถาม:"
echo ""
echo "gh auth login --with-token"
echo ""
echo "หรือใช้วิธีง่ายๆ:"
echo "echo 'YOUR_TOKEN_HERE' | gh auth login --with-token"
echo ""
echo "ขั้นตอนที่ 3: ทดสอบ"
echo "gh auth status"
echo ""
echo "=================================="
